spring.application.name=flowbot-service

server.port=80
server.servlet.context-path=/flowbot-service
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#couchBase URL
messenger.couchDbURL=${couchBaseUrl:10.128.0.7,10.128.0.8,10.128.0.9}
messenger.couchDbBucket=m1
jello.couchDbBucket=jello
orchestrator.payload.bucket=m1
userAgent.couchDbBucket=user
userAgent.idleTimeout=600

#pg-oauth
pg-oauth2.app-name = pg-oauth
pg-oauth2.token.expiry.time.diff = 100
pgOauth2.url=http://oauth-service.api/pgOauth
pgOauth2.urlString=${pgOauth2Url:http://oauth-service.api/pgOauth}

chimes.urlString=${chimesUrl:http://chimes-service.api/chimes/}

orchestrator.urlString=${orchURL:http://orchestrator-service.api/orchestrator}
orchestrator.debugNodeFlow=${orchestratorDebugNodeFlow:0}

logging.level.root=${rootloglevel:WARN}
